### ISSUE TITLE
Vive Microphone input lag when building for Windows in Unity 2017.2.0f3

### ISSUE THREAD

**Issue by ibilab** [keijiro/Reaktion#11]
In editor the Vive mic input is almost instant, same for the reactive animation. But when building (windows standalone 64) there is almost 1 second lag between input and reaction, and sometimes even an "echo" artifact, the input being repeated twice, can't find a way to debug this. Is it a known issue?
I've tried all latency settings, different sample rates, only one recording device active in Windows, tweaked SteamVR audio settings, same results.

For example building with 5.3.5 doesn't causes this problem, Vive mic is always super reactive, no matter what.

It might be how Unity 2017 handles default recording inputs or something in the player settings. Any ideas?

Thanks!

**Comment by keijiro** [comment]
I've abandoned this project (Reaktion) and now working on a project with a similar concept.

https://github.com/keijiro/Klak

Also I've developed a native plugin for low-latency audio input. This is much more stable than the previous solutions.

https://github.com/keijiro/KlakLasp

So, I recommend using Klak instead of Reaktion.

**Comment by keijiro** [comment]
I'm closing this ticket now. Please feel free to reopen for further questions.

**Comment by ibilab** [comment]
Ok that's awesome, i wasn't aware that Klak was similar to Reaktion and also tried Lasp combined with Reaktion at some point.
Thanks again!
